### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/dictyosperma-album#17]

**Comment by garrethil** [comment]
https://cdn.discordapp.com/attachments/1238132249300439122/1252397345874641006/Untitled_1.png?ex=66740bab&is=6672ba2b&hm=e142e76b106c157bf26f9f21b09e80e9452be5c3d5bfb0feb42bce25ce909007&

**Comment by topcowmoo** [comment]
Final logo

![Image](https://github.com/topcowmoo/dictyosperma-album/assets/149528212/f8f8a81b-ff13-4a0a-82ac-b55c200fe289)

**Comment by sbanati** [comment]
looks great, after seeing it on the page there are some considerations: 

1. Can we get rid of the shadow , its distracting 
2. Can we make a light / dark version as the color will be difficult in a dark mode

**Comment by topcowmoo** [comment]
final versions

![Untitled (2)](https://github.com/topcowmoo/dictyosperma-album/assets/149528212/a5d09b3d-0221-400d-89ab-1421402a4549)
![lilili copy](https://github.com/topcowmoo/dictyosperma-album/assets/149528212/0311a0c1-5b4d-42fa-8fe9-1171ee145953)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/dictyosperma-album/pull/43
