### ISSUE TITLE
create a column component

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/dictyosperma-album#39]

**Comment by garrethil** [comment]
![Image](https://github.com/topcowmoo/dictyosperma-album/assets/144272548/3214cb65-6637-402a-8dc6-c53d18944b8a)



![Image](https://github.com/topcowmoo/dictyosperma-album/assets/144272548/e55510a2-398d-4855-ba6a-d51d26ae5fa6)

**Comment by garrethil** [comment]
last thing would be the colored dots in the titles
